
MODULE_DIR = MODULE_A/module_a
PROJ_ROOT = ../../
SRC_DIR = .
TEST_DIR = unit_testing/tests
RUNNER_DIR = unit_testing/runners
OBJ_DIR = unit_testing/exe
ARTIFACTS_DIR = unit_testing/exe
EXE_DIR = unit_testing/exe
RESULTS_DIR = unit_testing/results
TEST_SRC_PREFIX = test_
TEST_SRC_SUFFIX = _tests
RUNNER_SRC_PREFIX = test_
RUNNER_SRC_SUFFIX = _runner
RESULTS_TXT_PREFIX =
RESULTS_TXT_SUFFIX = _results
include $(PROJ_ROOT)/unit_test/module_makefile
