#!../../tools/venv/bin/python3

import sys

sys.path.insert( 1, '../../tools/cmod/test' )
sys.path.insert( 2, '../../tools/cmod/config' )

from TestModule import test_local_module

# Module settings - manually edit if module change required
root_config_path = '../../config.ini'
module_settings_tag = 'DEFAULT_MODULE_STRUCTURE'
module_path = 'MODULE_A/module_a'

def main( verbosity ):
	test_local_module( module_path, module_settings_tag, root_config_path, verbosity )
	sys.exit()

if __name__ == "__main__":
	main( sys.argv[1:] )
