
MODULE_DIR = JOBQ
PROJ_ROOT = ../
SRC_DIR = .
TESTS_DIR = unit_testing/tests
RUNNER_DIR = unit_testing/runners
OBJ_DIR = unit_testing/exe
ARTIFACTS_DIR = unit_testing/exe
EXE_DIR = unit_testing/exe
RESULTS_DIR = unit_testing/results
RESULTS_TXT_PREFIX =
RESULTS_TXT_SUFFIX = _results
include $(PROJ_ROOT)/unit_test/module_makefile.mk
